config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "boards#index"

  resources :boards, only: [:show]
  resources :cells

  get "/js_solution" => "js_solutions#show", as: :js_solution
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :cells

  def find_cell_at(row:, column:)
    cells.select { |c| c.row == row && c.column == column }[0]
  end

  def make_server_move
    cell = cells.select { |c| c.content.nil? }[0]
    cell.fill_in_with "X"
  end
end

app/models/cell.rb
class Cell < ApplicationRecord
  class ContentAlreadyExists < Exception; end

  belongs_to :board

  def fill_in_with(value)
    raise ContentAlreadyExists if content
    update_attributes(content: value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find params[:id]
    @row1 = @board.cells.select { |c| c.row == "1" }
    @row2 = @board.cells.select { |c| c.row == "2" }
    @row3 = @board.cells.select { |c| c.row == "3" }
  end
end

app/controllers/cells_controller.rb
class CellsController < ApplicationController
  def update
    @cell = Cell.find params[:id]
    @board = @cell.board
    begin
      @cell.fill_in_with "O"
      @board.make_server_move
      render json: json_response
    rescue Cell::ContentAlreadyExistsError
      render status: 500
    end
  end


  protected

  def json_response
    json = "["
    @board.cells.each do |cell|
      json << cell.to_json
    end
    json << "]"
    json.to_json
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/js_solutions_controller.rb
class JsSolutionsController < ApplicationController
  layout "js"

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/index.html.erb
<h1>Tic Tac Toe Boards</h1>

<p>
  <%= link_to "View JS Solution", js_solution_path %>
</p>

<ul>
  <% @boards.each do |board| %>
    <li><%= link_to "Board #{board.id}", board %></li>
  <% end %>
</ul>

app/views/boards/show.html.erb
<h1>Tic Tac Toe</h1>

<div id="board">
  <div class="row" id="row-1">
    <% @row1.each do |cell| %>
      <%= render cell %>
    <% end %>
  </div>
  <div class="row" id="row-2">
    <% @row2.each do |cell| %>
      <%= render cell %>
    <% end %>
  </div>
  <div class="row" id="row-3">
    <% @row3.each do |cell| %>
      <%= render cell %>
    <% end %>
  </div>
</div>

app/views/cells/_cell.html.erb
<span class="cell" id="cell_<%= cell.id %>"><%= cell.content %></span>

app/views/js_solutions/show.html.erb
<h1>Tic Tac Toe in Javascript!</h1>

<div id="board">
  <p id="result">Game in progress...</p>

  <div id="row-1" class="row">
    <span id="cell-1-1" class="cell"></span>
    <span id="cell-1-2" class="cell"></span>
    <span id="cell-1-3" class="cell"></span>
  </div>
  <div id="row-2" class="row">
    <span id="cell-2-1" class="cell"></span>
    <span id="cell-2-2" class="cell"></span>
    <span id="cell-2-3" class="cell"></span>
  </div>
  <div id="row-3" class="row">
    <span id="cell-3-1" class="cell"></span>
    <span id="cell-3-2" class="cell"></span>
    <span id="cell-3-3" class="cell"></span>
  </div>
</div>

<input type="checkbox" checked />When the user visits the site, they see an empty tic tac toe board.<br />
<input type="checkbox" checked />Moves are made by clicking in desired cell on the board.<br />
<input type="checkbox" checked />The user is always O, so they go first.<br />
<input type="checkbox" checked />The server plays as X. For the purpose of this prototype, the server plays the first available move, from left to right, top to bottom. This will make testing easy at the end.<br />
<input type="checkbox" checked />If the user clicks on an occupied cell, nothing should happen.<br />
<input type="checkbox" checked />The server must determine if the game is over, and report that to the client.<br />
<input type="checkbox" checked />After the first request (to load the html/css/js), requests should be async. (AJAX).<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dobt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/js.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dobt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <%= javascript_pack_tag "game" %>
</html>